<?php
/*
 * Plugin Name: Playground SEO Meta Tag
 * Description: My first machine-facing SEO plugin. It injects meta descriptions for Google.
 * Author: GRA
 */

function add_playground_meta_description() {
    
    // 1. CONDITIONAL: Only run this if we are looking at a specific blog post
    if ( is_singular() ) {
        
        // 2. GET DATA: Grab the custom excerpt (summary) from the WordPress database
        $summary = get_the_excerpt();
        
        // Fallback: If we forgot to write a summary, use a default sentence
        if ( empty( $summary ) ) {
            $summary = "This is a default SEO description generated by my plugin.";
        }
        
        // 3. CLEAN UP: Strip out any weird formatting
        $clean_summary = strip_tags( $summary );
        
        // 4. PRINT TO HEAD: Echo the exact HTML that Google bots are looking for
        echo "\n" . '<!-- Added by GRA SEO Plugin -->' . "\n";
        echo '<meta name="description" content="' . esc_attr( $clean_summary ) . '" />' . "\n";
    }
}

// Attach our function to the <head> of the website
add_action('wp_head', 'add_playground_meta_description');
